var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/shows/page.js")
R.c("server/chunks/ssr/0x1i_06qhgr0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11zd536._.js")
R.c("server/chunks/ssr/0x1i_next_dist_esm_03ftsek._.js")
R.c("server/chunks/ssr/0x1i_next_dist_compiled_1292cez._.js")
R.c("server/chunks/ssr/0x1i_next_dist_server_route-modules_app-page_0bnmoku._.js")
R.c("server/chunks/ssr/[externals]__0n13xf4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12a5_55._.js")
R.c("server/chunks/ssr/0x1i_next_dist_client_components_0g966gs._.js")
R.c("server/chunks/ssr/0x1i_next_dist_client_components_builtin_forbidden_0ecg2s8.js")
R.c("server/chunks/ssr/0x1i_next_dist_client_components_builtin_unauthorized_0f.7-fe.js")
R.c("server/chunks/ssr/0x1i_next_dist_client_components_builtin_global-error_0dx08i..js")
R.c("server/chunks/ssr/primakavi-show-portal_app_admin_12njgdb._.js")
R.c("server/chunks/ssr/0x1i_next_0ui9jse._.js")
R.c("server/chunks/ssr/0x1i_@supabase_postgrest-js_dist_index_mjs_0n3ratn._.js")
R.c("server/chunks/ssr/0x1i_@supabase_auth-js_dist_module_0fjxpip._.js")
R.c("server/chunks/ssr/0x1i_05kae00._.js")
R.c("server/chunks/ssr/primakavi-show-portal_0_br37u._.js")
R.m("[project]/primakavi-show-portal/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/shows/page { METADATA_0 => \"[project]/primakavi-show-portal/app/favicon.ico.mjs { IMAGE => \\\"[project]/primakavi-show-portal/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_1 => \"[project]/primakavi-show-portal/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/primakavi-show-portal/app/admin/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/primakavi-show-portal/app/admin/shows/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/primakavi-show-portal/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/shows/page { METADATA_0 => \"[project]/primakavi-show-portal/app/favicon.ico.mjs { IMAGE => \\\"[project]/primakavi-show-portal/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_1 => \"[project]/primakavi-show-portal/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/primakavi-show-portal/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/primakavi-show-portal/app/admin/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/primakavi-show-portal/app/admin/shows/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
