var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/show/[token]/files/route.js")
R.c("server/chunks/primakavi-show-portal_app_api_show_[token]_files_route_ts_0wwcqoc._.js")
R.c("server/chunks/0x1i_next_0vekb10._.js")
R.c("server/chunks/0x1i_@supabase_postgrest-js_dist_index_mjs_12plbbs._.js")
R.c("server/chunks/0x1i_@supabase_auth-js_dist_module_0p113lp._.js")
R.c("server/chunks/0x1i_0s9ol6i._.js")
R.c("server/chunks/[root-of-the-server]__0iqewfe._.js")
R.c("server/chunks/0egh__next-internal_server_app_api_show_[token]_files_route_actions_0y0dkj..js")
R.m("[project]/primakavi-show-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/primakavi-show-portal/app/api/show/[token]/files/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/primakavi-show-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/primakavi-show-portal/app/api/show/[token]/files/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
